name: pawtrack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1          # For Firebase initialization
  firebase_auth: ^5.5.1           # For Firebase authentication
  provider: ^6.1.1                # For state management (ThemeProvider)
  flutter_svg: ^2.0.9             # For SVG logo rendering
  shared_preferences: ^2.2.2      # For local persistence (welcome screen, pets)
  flutter_localizations:          # For localization support (from Part-1)
    sdk: flutter
  flutter_dotenv: ^5.1.0          # For loading .env file with Firebase config
  geolocator: ^12.0.0             # Added for location tracking in LocationTrackerPage
  flutter_animate: ^4.5.0         # Added for AnimatedButton animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0           # For linting and code quality

flutter:
  uses-material-design: true
  assets:
    - assets/images/paw_heart_dark_logo.svg
    - assets/images/paw_heart_light_logo.svg
    - .env                        # Environment file for Firebase credentials