name: pawtrack
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_auth_platform_interface: ^7.6.1
  firebase_database: ^11.3.4
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.3
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^17.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.35.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/paw_heart_dark_logo.png"  # Path to the PNG file

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/paw_heart_light_logo.svg  # Path to the SVG file
    - assets/images/paw_heart_dark_logo.png
    - .env  # Other assets if needed